<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caseylucas/first/v1/first_api.proto

namespace GPBMetadata\Caseylucas\First\V1;

class FirstApi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3020a2363617365796c756361732f66697273742f76312f6669727374" .
            "5f6170692e70726f746f121363617365796c756361732e66697273742e76" .
            "31221e0a0b4563686f52657175657374120f0a076d657373616765180120" .
            "012809221f0a0c4563686f526573706f6e7365120f0a076d657373616765" .
            "18012001280932570a084669727374415049124b0a044563686f12202e63" .
            "617365796c756361732e66697273742e76312e4563686f52657175657374" .
            "1a212e63617365796c756361732e66697273742e76312e4563686f526573" .
            "706f6e736542650a17636f6d2e63617365796c756361732e66697273742e" .
            "7631420d466972737441706950726f746f50015a0766697273747631a202" .
            "03434658aa021343617365796c756361732e46697273742e5631ca021343" .
            "617365796c756361735c46697273745c5631620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

